config/routes.rb
Rails.application.routes.draw do
  devise_for :refuges
  devise_for :users
  root to: 'pages#home'
  get 'profile', to: 'pages#profile', as: :profile
  get 'refuge_dashbord', to: 'pages#refuge_dashbord', as: :refuge_dashbord

  resources :refuges do
    resources :animals, except: [:destroy]
      resources :likes
  end
  resources :animals, only: [:destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/adoption.rb
class Adoption < ApplicationRecord
  belongs_to :animal
  belongs_to :user
end

app/models/animal.rb
class Animal < ApplicationRecord
  SPECIE = ["Dog", "Cat"]
  belongs_to :refuge
  has_many :adoptions
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :refuge
  belongs_to :user
end

app/models/refuge.rb
class Refuge < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true
  has_many :animals
  has_many :likes, dependent: :destroy

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :adoptions

  validates :last_name, :first_name, presence: true
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  before_action :set_animal, only: [:edit, :update, :destroy]
  before_action :set_refuge, only: [:create, :edit]


  def create
    @animal = Animal.new(params_animal)
    @refuge = Refuge.find(params[:refuge_id])
    @animal.refuge = @refuge
    if @animal.save
      redirect_to refuge_path(@refuge)
    else
      render :new
    end
  end

  def edit
    @refuge = Refuge.find(params[:refuge_id])
  end

  def update
    @animal.update(params_animal)
    if @animal.save
      redirect_to refuge_dashbord_path
    else
      render :new
    end
  end

  def destroy
    @animal.destroy
    redirect_to refuge_dashbord_url, notice: 'Reservation was successfully destroyed.'
  end

  private

  def params_animal
    params.require(:animal).permit(:name, :species, :age, :description)
  end

  def set_animal
    @animal = Animal.find(params[:id])
  end

  def set_refuge
    @refuge = refuge.find(params[:refuge_id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :birth_date, :adress, :username, :name, :postcode, :address, :city])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :birth_date, :adress, :username, :name, :postcode, :addres, :city])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :find_refuge
  before_action :find_like, only: [:destroy]

  def create
    if already_liked?
      flash[:notice] = "You can't like more than once"
    else
      @refuge.likes.create(user: current_user)
    end
    redirect_to refuge_path(@refuge)
  end

  def destroy
    if !(already_liked?)
      flash[:notice] = "Cannot unlike"
    else
      @like.destroy
    end
    redirect_to refuge_path(@refuge)
  end

  private

  def find_refuge
    @refuge = Refuge.find(params[:refuge_id])
  end

  def already_liked?
    Like.where(user_id: current_user.id, refuge_id:
    params[:refuge_id]).exists?
  end

  def find_like
   @like = @refuge.likes.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end

  def profile
    @user = current_user
  end

  def refuge_dashbord
    @refuge = current_refuge
    @animals = Animal.where(refuge: current_refuge)
    @animal = @refuge.animals
    @animal = Animal.new
  end
end

app/controllers/refuges_controller.rb
class RefugesController < ApplicationController
  before_action :set_refuge, only: [:show]
  def index
    @refuges = Refuge.all
  end

  def show

  end

  private

  def set_refuge
    @refuge = Refuge.find(params[:id])
  end

  def refuge_params
    params.require(:refuge).permit[:name, :address, :postcode, :city]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/animals/_animalform.html.erb
<div class="container">
<%= simple_form_for [@refuge, @animal] do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :age %>
    <%= f.input :species, collection: Animal::SPECIE %>
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit , class: "orange-btn" %>
  </div>
<% end %>
</div>

app/views/animals/edit.html.erb
<%= render "animalform" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SpaProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container">
<h1>Adopt a friend !</h1>
<p>Trouves ton compagnon autour de chez toi !</p>
<div class="row">
      <div class="col-lg-6">
          <div class="card mb-4 rounded-3 shadow-sm">
          <div class="card-header py-3">
            <h4 class="my-0 fw-normal">Find your Partner</h4>
          </div>
          <div class="card-body">
            <h1 class="card-title pricing-card-title">Sign Up</h1>
            <%= link_to "Sign Up", new_user_registration_path, class: "w-100 btn btn-lg btn-outline-primary" %>
          </div>
        </div>
      </div><!-- /.col-lg-4 -->
      <div class="col-lg-6">
          <div class="card mb-4 rounded-3 shadow-sm">
          <div class="card-header py-3">
            <h4 class="my-0 fw-normal">SPA</h4>
          </div>
          <div class="card-body">
            <h1 class="card-title pricing-card-title">Click below to get started</h1>

            <%= link_to "Sign Up", new_refuge_registration_path, class: "w-100 btn btn-lg btn-outline-primary" %>
          </div>
        </div>
      </div><!-- /.col-lg-4 -->
      <%= link_to "Voir les refuges", refuges_path  %>
  </div>
</div>

app/views/pages/profile.html.erb
<h1>Hello <%= @user.username %> !<h1>

<h2>Vos informations :</h2>
<ul>
<li>Prénom : <%= @user.first_name %></li>
<li>Nom : <%= @user.last_name %></li>
<li>Adresse : <%= @user.adress %></li>
<li>Date de naissance : <%= @user.birth_date %></li>
</ul>

app/views/pages/refuge_dashbord.html.erb
<h1>Hello <%= @refuge.name %> !<h1>

<h2>Vos informations :</h2>
<ul>
<li>Adresse : <%= @refuge.address %></li>
<li>Code Postal : <%= @refuge.postcode %></li>
<li>Ville : <%= @refuge.city %></li>
</ul>

<h2>Vos animaux à l'adoption :</h2>
<% @animals.each do |animal| %>
<ul>
<li>Nom: <%= animal.name %></li>
</ul>
<% end %>


<h4>Ajouter un nouveau pensionnaire :</h4>
 <%= render "animals/animalform", refuge: @refuge, animal: @animal %>

app/views/refuges/index.html.erb
<% @refuges.each do |refuge| %>
<div class="card" style="width: 18rem;">
  <img class="card-img-top" src="..." alt="Card image cap">
  <div class="card-body">
      <h3><%= link_to refuge.name, refuge_path(refuge) %></h3>
      <p><%= refuge.likes.count %> <%= (refuge.likes.count) == 1 ? 'Like' : 'Likes'%></p>
  </div>
</div>
<% end %>

app/views/refuges/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/refuges/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/refuges/show.html.erb
  <div class="container">

    <div class="refuge-info">
      <h1><%= @refuge.name %></h1>
        <h3>Bonjour à tous et bienvenue sur la page de notre refuge ! Vous trouverez sur cette page toutes nos informations et nos pensionnaires à l'adoption !</h3>
        <%= @refuge.address %> <%= @refuge.postcode %> <%= @refuge.city %>
    </div>
      <div class="refuge-animal">
        <% @refuge.animals.each do |animal| %>
          <h1><%= animal.name %></h1>
          <h2><%= animal.species %></h2>
          <h2><%= animal.age %> ans</h2>
            <h3><%= animal.description %></h3>
            <%= link_to "edit", edit_refuge_animal_path(@refuge, animal) %>
          <% end %>
      </div>
      <% if user_signed_in? %>
      <% pre_like = @refuge.likes.find { |like| like.user_id == current_user.id} %>
        <% if pre_like %>
          <%= button_to 'Unlike', refuge_like_path(@refuge, pre_like), method: :delete %>
        <% else %>
           <%= button_to 'Like', refuge_likes_path(@refuge), method: :post %>
        <% end %>
        <% end %>
      <p><%= @refuge.likes.count %> <%= (@refuge.likes.count) == 1 ? 'Like' : 'Likes'%></p>
  </div>

<%= link_to "Retour aux refuges", refuges_path, class:"btn btn-primary" %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <i class="fa-solid fa-paw"></i>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Profil", profile_path, class: "dropdown-item" %>
              <%= link_to "Demande Adoption", "#", class: "dropdown-item" %>
              <%= link_to "Se Déconnecter", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "User Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
         <% if refuge_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Dashbord", refuge_dashbord_path, class: "dropdown-item" %>
              <%= link_to "Demande Adoption", "#", class: "dropdown-item" %>
              <%= link_to "Se Déconnecter", destroy_refuge_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Refuge Login", new_refuge_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>